import { expect, test } from "@playwright/test";

test(`PVR Cinemas`,async({page})=>{
    await page.goto('https://www.pvrcinemas.com/')
    await page.waitForTimeout(2000)
    //await page.locator('(//span[@class="cities-placed"])[2]').click()
    await page.locator('//div[@class="cities-overlay cities-active"]/following-sibling::h6[text()="Chennai"]').click()
    await page.locator('//span[text()="Cinema"]').click()
    await page.locator('//span[text()="Select Cinema"]').click()
    await page.locator('//span[text()="PVR Sathyam Royapettah Chennai"]').click()
    await page.locator('//span[contains(text(),"Today")]').click()
    await page.locator('//span[text()="SATTENDRU MAARUDHU VAANILAI"]').click()
    await page.locator('//span[text()="10:45 PM"]').click()
    await page.getByRole('button',{name:'Submit'}).click()
    await page.locator('//button[text()="Accept"]').click()
    await expect(page.locator('[id="EL.ELITE|H:2"]')).toBeVisible()
    await page.locator('[id="EL.ELITE|H:2"]').click()
    let seatNum = await page.locator('(//div[@class="seat-info"]//ancestor::p)[2]').last().innerText()
    console.log(`Seat: ${seatNum}`)
    let amt = await page.locator('//div[@class="grand-amount"]//h6').last().innerText()
    console.log(`Amount: ${amt}`)
    await page.getByRole('button',{name:'Proceed'}).click()
    await page.waitForTimeout(3000)
    await expect(page).toHaveTitle('PVR Cinemas')
})