import {chromium, expect, test} from "@playwright/test"

test("Create Lead",async()=>{
    let inputComName = 'US2'
    let inputFirName = 'Hari2'
    let inputLasName = 'Saha2'
    const browser = await chromium.launch({channel:'msedge',headless:false,args:['--start-maximized']})
    const context = await browser.newContext({viewport:null,deviceScaleFactor: undefined})
    const page = await context.newPage()
    await page.goto(`https://leaftaps.com/opentaps/control/main`)
    await page.waitForTimeout(2000)
    await page.locator('#username').fill("democsr2")
    await page.locator('#password').fill("crmsfa")
    await page.locator('.decorativeSubmit').click()
    await page.waitForTimeout(2000)
    await console.log(`Page title is ${(await (page.title()))}`)
    await page.locator("//a[contains(text(),'CRM/SFA')]").click()
    await page.waitForTimeout(2000)
    await console.log(`Page title is ${(await (page.title()))}`)
    await page.locator("//a[text()='Create Lead']").click()
    await page.locator('#createLeadForm_companyName').fill(inputComName,{timeout:2000})
    await page.locator('#createLeadForm_firstName').fill(inputFirName)
    await page.locator('#createLeadForm_lastName').fill(inputLasName)
    await page.locator("#createLeadForm_personalTitle").fill("Mr")
    await page.locator("#createLeadForm_generalProfTitle").fill("Mr")
    await page.locator("#createLeadForm_annualRevenue").fill("500000")
    await page.locator("#createLeadForm_departmentName").fill("IT")
    await page.locator("#createLeadForm_primaryPhoneNumber").fill("9876543210")
    await page.locator("//input[@value='Create Lead']").click()
    await console.log(`Page title is ${(await (page.title()))}`)
    let cname = await page.locator('#viewLead_companyName_sp').innerText()
    let fname = await page.locator('#viewLead_firstName_sp').innerText()
    let lname = await page.locator('#viewLead_lastName_sp').innerText()
    let status = await page.locator('#viewLead_statusId_sp').innerText()
    await expect(cname).toContain(inputComName)
    await expect(fname).toBe(inputFirName)
    await expect(lname).toBe(inputLasName)
    await expect(status).toBe('Assigned')
    console.log(`Lead Created successsfully. Details ${cname} ${fname} ${lname} ${status}`)
})