import { test,expect } from "@playwright/test";

test('Service Now Test',async({page})=>{
    await page.goto('https://dev331650.service-now.com/')
    await page.locator('#user_name').fill('admin') 
    await page.locator('#user_password').fill('Ig@-R6iFfOv1')
    await page.locator('#sysverb_login').click()
    await page.waitForEvent('domcontentloaded')
    await page.getByRole('menuitem',{name:'All'}).click()
    await page.getByRole('link',{name:'Service Catalog 3 of 23'}).click()
    await page.waitForTimeout(5000)
    const allFrames = page.frames()
    console.log(`Number of frames: ${allFrames.length}`)
    const firstFrame = await page.frameLocator('[title="Main Content"]')
    await firstFrame.locator('//h2[contains(text(),"Mobiles")]').click()
    await page.waitForTimeout(8000)
    const secondFrame = await page.frameLocator('[title="Main Content"]')
    await secondFrame.getByRole('link',{name:'Apple iPhone 13 pro',exact:true}).click()
    const thirdFrame = await page.frameLocator('[title="Main Content"]')
    await thirdFrame.locator('//label[text()="Yes"]').click()
    await thirdFrame.getByRole('textbox',{name:'What was the original phone number?',exact:false}).fill('99')
    const dd = await thirdFrame.getByRole('combobox',{name:'must be populated before Submit',exact:false})
    await dd.selectOption({value:'unlimited'})
    await thirdFrame.locator('//label[text()="Sierra Blue"]').click()
    await thirdFrame.locator('//label[contains(text(),"512 GB")]').click()
    await thirdFrame.locator('#oi_order_now_button').click()
    const fourthFrame = await page.frameLocator('[title="Main Content"]')
    await expect(fourthFrame.locator('//span[text()="Thank you, your request has been submitted"]')).toBeVisible()
    await page.screenshot({path:'screenshots/confirmed.png'})
    await page.waitForTimeout(3000)

})